sudo: required

services:
  - docker

language: java
jdk: openjdk11

env:
  global:
    - IMAGE_NAME="$DOCKER_GCP_LOCATION/ssdc-rm-notify-service"

before_install:
  - mvn fmt:check
  - docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  - docker network create ssdcrmdockerdev_default
  - echo "$DOCKER_GCP_PASSWORD" > ~/google-service-account-key.json
  - export GOOGLE_APPLICATION_CREDENTIALS=~/google-service-account-key.json

install: echo "SKIPPING DEFAULT INSTALL" # Travis has a default maven install. Don't build twice!

script: travis_wait mvn verify jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - main
