spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/rm
    username: appuser
    password: postgres
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8538
        project-id: our-project


notify:

  wcis-service:
    base-url: http://notifystub:5000
    api-key: dummykey-ffffffff-ffff-ffff-ffff-ffffffffffff-ffffffff-ffff-ffff-ffff-ffffffffffff
    sender-id: 6bf5f8c2-bc4e-4bbc-a855-aa708d5fdfe7
  test-service:
    base-url: http://notifystub:5000
    api-key: dummykey-ffffffff-ffff-ffff-ffff-ffffffffffff-ffffffff-ffff-ffff-ffff-ffffffffffff
    sender-id: 6bf5f8c2-bc4e-4bbc-a855-aa708d5fdfe7

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8667
