server:
  port: 8162
spring:
  task:
    scheduling:
      pool:
        size: 10

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          lob:
            non_contextual_creation: true

  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 100

exceptionmanager:
  connection:
    scheme: http

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

queueconfig:
  sms-fulfilment-topic: rm-internal-sms-fulfilment
  sms-request-enriched-topic: rm-internal-sms-request-enriched
  sms-request-subscription: rm-internal-sms-request_notify-service
  sms-request-enriched-subscription: rm-internal-sms-request-enriched_notify-service
  email-fulfilment-topic: rm-internal-email-fulfilment
  email-request-enriched-topic: rm-internal-email-request-enriched
  email-request-subscription: rm-internal-email-request_notify-service
  email-request-enriched-subscription: rm-internal-email-request-enriched_notify-service


notify:
  apiKey: dummykey-ffffffff-ffff-ffff-ffff-ffffffffffff-ffffffff-ffff-ffff-ffff-ffffffffffff
  baseUrl: https://dummy-notify:123
  senderId: 6bf5f8c2-bc4e-4bbc-a855-aa708d5fdfe7

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  health:
    pubsub:
      enabled: false
  metrics:
    tags:
      application: Notify Service
      pod: ${HOSTNAME}
    export:
      stackdriver:
        project-id: dummy-project-id
        enabled: false
        step: PT1M

messagelogging:
  logstacktraces: false

sms-request-enriched-delay: 0  # milliseconds
email-request-enriched-delay: 0  # milliseconds

logging:
  profile: DEV
  level:
    root: INFO
    com.google.cloud.spring.pubsub.integration.inbound.PubSubInboundChannelAdapter: ERROR
